theme: jekyll-theme-minimal
show_downloads: false
title: UCL Computer Science PGTA info
description: Process and guidance for CS or eligible IEP modules that need Postgraduate Teaching Assistants (PGTA).
baseurl: /pgta

docs_list_title: PGTA information
docs:

- title: Home
  url: ./index.html

- title: HR information for MLs and PGTAs
  url: ./ml.html

- title: Information for Module Leads (ML)
  url: ./ml.html

- title: Information for PGTAs (RA)
  url: ./ra.html

- title: Information for PGTAs (PhD)
  url: ./phd.html

- title: Contact
  url: ./contact.html

- title: How to calculate TA hours
  url: ./hours.html