theme: jekyll-theme-minimal
show_downloads: false
title: UCL Computer Science - Postgraduate Teaching Assistants (PGTAs) for 2022/23
description: Process and guidance for CS or eligible IEP module in any term of the coming academic year that need Postgraduate Teaching Assistants (PGTA). These can be Research Student Teaching Assistants (TAs) or Research Associates (RAs).
