theme: jekyll-theme-minimal
show_downloads: false
title: UCL Computer Science Postgraduate Teaching Assistants
description: Process and guidance for CS or eligible IEP modules that need Postgraduate Teaching Assistants (PGTA).
