theme: jekyll-theme-minimal
show_downloads: false
title: UCL Computer Science PGTA info
description: Process and guidance for CS or eligible IEP modules that need Postgraduate Teaching Assistants (PGTA).